name: "PR Chunking"
description: "Automatically creates PRs when a list of commits exceeds a defined threshold"
inputs:
  access-token:
    description: "Github access token"
    required: true
  max-diff:
    description: "Maximum number of changes before creating a PR"
    required: true
    default: "30"
  base-branch:
    description: "The name of the base branch"
    required: true
    default: "staging"
  base-branch:
    description: "The name of the main branch"
    required: true
    default: "develop"
runs:
  using: "node12"
  main: "dist/index.js"
